### ISSUE TITLE
Build Failure w/ Proguard enabled

### ISSUE THREAD

**Issue by jkane001** [taplytics/Taplytics-Android-SDK#15]
@VicV  With the update to Taplytics 1.9.0, I get an error building with Proguard enabled. The error says something about "expected { but found ; on line 190 of proguard.txt" (it includes the path to the Taplytics proguard file which is copied below. Line 190 is this:

-keep public class com.taplytics.sdk.TLGcmBroadcastReceiver; - presumably the trailing ";" should simply be deleted.

-------------------------------------------------------------------------------------------------------------------------
Full proguard.txt file:
-------------------------------------------------------------------------------------------------------------------------
#-dontshrink
-dontnote
#-dontoptimize
-keepattributes Exceptions,LineNumberTable,Signature,*Annotation*,SourceFile
#-keepparameternames
#-renamesourcefileattribute SourceFile
#-optimizations !code/simplification/arithmetic

-keepclassmembers class * extends java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

-dontwarn io.socket.**
-dontwarn com.taplytics.**
-dontwarn okio.**
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

-keep public class com.taplytics.sdk.Taplytics {
    public protected <fields>;
    public protected <methods>;
	public protected *;
}

-keep public interface com.taplytics.sdk.TaplyticsPushNotificationListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsPushNotificationIntentListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsDelayLoadListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsResetUserListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsPushTokenListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsNewSessionListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsRunningExperimentsListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsVarListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.CodeBlockListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsExperimentsLoadedListener {
	public protected *;
	<methods>;
}

-keep public class com.taplytics.sdk.TaplyticsVar {*;}

-keepnames  public class com.taplytics.sdk.TaplyticsVar

-keep public interface com.taplytics.sdk.CodeBlockListener {
	public protected *;
	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsPushOpenedListener {
  	public protected *;
  	<methods>;
}

-keep public interface com.taplytics.sdk.TaplyticsPushSubscriptionChangedListener {
	public protected *;
	<methods>;
}

-keepnames public class com.taplytics.sdk.TLGcmIntentService
-keepnames public class com.taplytics.sdk.TLGeofenceEventService
-keep public class com.taplytics.sdk.TLBootReceiver
-keep public class com.taplytics.sdk.TLGcmBroadcastReceiver;

-keep public class com.taplytics.sdk.TLGcmBroadcastReceiver {
		public protected *;
    	<methods>;
}

# Also keep - Enumerations. Keep the special static methods that are required in
# enumeration classes.
-keepclassmembers enum  * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class * extends java.util.ListResourceBundle {
    protected Object[][] getContents();
}

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
    public static final *** NULL;
}

-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
    @com.google.android.gms.common.annotation.KeepName *;
}

-keepnames class * implements android.os.Parcelable {
    public static final ** CREATOR;
}

#Keeping google play services class that we use reflection for
-keep public class com.google.android.gms.gcm.GoogleCloudMessaging{
	*;
}
-keep public class com.google.android.gms.location.GeofencingEvent{
	*;
}
-keep public class com.google.android.gms.location.Geofence{
	*;
}
-keep public class com.google.android.gms.common.api.GoogleApiClient$Builder{
	*;
}
-keep public class com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener{
	*;
}
-keep public class com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks{
	*;
}
-keep public class com.google.android.gms.location.LocationServices{
	*;
}
-keep public class com.google.android.gms.common.api.GoogleApiClient{
	*;
}
-keep public class com.google.android.gms.analytics.Tracker{
	*;
}

-keepclassmembernames public class android.support.v7.widget.RecyclerView{
	*;
}

-keepclassmembernames public class android.widget.AbsListView{
	*;
}

-keep class android.support.v4.app.Fragment {
    *;
 }

-keep class android.support.v4.view.ViewPager

-keepclassmembers class android.support.v4.view.ViewPager$LayoutParams {
    *;
}

-keep class com.mixpanel.android.mpmetrics.MixpanelAPI { *;}

-keep class com.flurry.android.FlurryAgent { *; }

#Keeping recyclerView and listView stuff so that doesn't get obfuscated away

**Comment by jkane001** [comment]
The exact text of the error message is: "Expecting opening '{' at ';' in line 104 of file 'C:\Users\Jeremy\My Projects\Wakey\app\build\intermediates\exploded-aar\com.taplytics.sdk\taplytics\1.9.0\proguard.txt'"

**Comment by VicV** [comment]
@jkane001 do a `./gradlew clean build --refresh-dependencies`

I'm pretty sure I shortly right after I released it, so I didn't do a vernum bump. 

Let me know.

**Comment by jkane001** [comment]
Did that, still get the same result. Perhaps a version bump is needed after
all?

**Comment by VicV** [comment]
I guess so. I'm trying to find out how it passed my CI right now.

**Comment by VicV** [comment]
@jkane001 try that again. I had uploaded the wrong file.

**Comment by VicV** [comment]
https://github.com/taplytics/Taplytics-Android-SDK/releases/tag/1.9.1

**Comment by jkane001** [comment]
That seems to have fixed it - thanks!
